name: aa
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.3+5

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_onboard:
  shared_preferences:
  carousel_slider: ^5.0.0
  flutter_bloc:
  bloc:
  fluttertoast: ^8.2.1
  conditional_builder_null_safety:
  url_launcher:
  card_loading: ^0.3.2
  dio:
  http_parser: ^4.0.2
  file_picker:
  image_picker:
  animated_bottom_navigation_bar: ^1.3.3
  ionicons: ^0.2.2
  fw_tab_bar: ^0.0.3
  google_nav_bar: ^5.0.7
  font_awesome_flutter: ^10.9.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/home/


  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo/static/Cairo-Bold.ttf
